// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb1exXyJfWkCiV3mWXl21V_Hy1ff1XerY',
    appId: '1:241005718118:web:a8c6fbe65379d339541ba7',
    messagingSenderId: '241005718118',
    projectId: 'movies-24dab',
    authDomain: 'movies-24dab.firebaseapp.com',
    storageBucket: 'movies-24dab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq19-ykW_T3XfRkUR17HqJBzOed6CAiQo',
    appId: '1:241005718118:android:d21aa6def32b062f541ba7',
    messagingSenderId: '241005718118',
    projectId: 'movies-24dab',
    storageBucket: 'movies-24dab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnRuVY9D7KVdPy92U-2OufKJ3mMAwjQ4U',
    appId: '1:241005718118:ios:de6ac08f318352da541ba7',
    messagingSenderId: '241005718118',
    projectId: 'movies-24dab',
    storageBucket: 'movies-24dab.appspot.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnRuVY9D7KVdPy92U-2OufKJ3mMAwjQ4U',
    appId: '1:241005718118:ios:cf84b87740006acf541ba7',
    messagingSenderId: '241005718118',
    projectId: 'movies-24dab',
    storageBucket: 'movies-24dab.appspot.com',
    iosBundleId: 'com.example.movies.RunnerTests',
  );
}
